services:
  app:
    build:
      context: ./flight-diary-frontend
      dockerfile: dev.Dockerfile
      target: development
    container_name: flight-diary-frontend-dev
    ports:
      - '${VITE_PORT:-5173}:5173'
    volumes:
      - ./flight-diary-frontend/src:/usr/src/app/src:ro
      - ./flight-diary-frontend/package.json:/usr/src/app/package.json
      - ./flight-diary-frontend/vite.config.ts:/usr/src/app/vite.config.ts:ro

  server:
    build:
      context: ./flight-diary-backend
      dockerfile: dev.Dockerfile
      target: development
    container_name: flight-diary-backend-dev
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    volumes:
      - ./flight-diary-backend/src:/usr/src/app/src:ro
      - ./flight-diary-backend/package.json:/usr/src/app/package.json
