services:
  app:
    build:
      context: ./flight-diary-frontend
      dockerfile: dev.Dockerfile
      target: development
    container_name: flight-diary-frontend-dev
    volumes:
      - ./flight-diary-frontend/src:/usr/src/app/src:ro
      - ./flight-diary-frontend/package.json:/usr/src/app/package.json
      - ./flight-diary-frontend/vite.config.ts:/usr/src/app/vite.config.ts:ro

  server:
    build:
      context: ./flight-diary-backend
      dockerfile: dev.Dockerfile
      target: development
    container_name: flight-diary-backend-dev
    volumes:
      - ./flight-diary-backend/src:/usr/src/app/src:ro
      - ./flight-diary-backend/package.json:/usr/src/app/package.json

  nginx:
    image: nginx:trixie-perl
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '${PROXY_PORT:-8080}:80'
    container_name: flight-diary-proxy-dev
    depends_on:
      - app
      - server
