events { }

http {
  server {
    listen 80;
    location / {
      # Pass request to app
      proxy_pass http://app:80;
    }

    location /api {
       # Have to pass proxy to backend. vite.config.ts does not work in production mode
       proxy_pass http://server:3000;
    }
  }
}